### ISSUE TITLE
The sync "all" option runs asynchronously from the dashboard

### ISSUE THREAD

**Issue by themarcusbattle** [marcusbattle/press-sync#19]
The ideal way to fix this is to add the parameter "async: false" to the syncData() method in press-sync.js, but @phatsk reported memory issues with this implementation. Logging an issue here so that more research can be done to create a more performant solution. 

In the meantime you may notice that using "all" will complete the sync as desired, but jumble the order of the objects as they are communicated via the dashboard.

**Comment by phatsk** [comment]
We can use something similar to the session option in `feature/store-synced-posts` where an option of what needs to sync and what is syncing, and on each page we can pop that option when the objects for that option are finished. Example:

- Start Press Sync for ALL
- ALL option gets set 
  - update_option( 'syncing_all', [ 'users', 'media', 'posts' ] )
- Start syncing users
  - When users is done
  - update_option( 'syncing_all', ['media', 'posts'] )
- Start syncing media
- etc

This is just an idea, not sure how feasible it actually is.

I think if we can come up with some mechanism for looping the ALL types on the server then we can avoid having to loop them in the browser. 

Another alternative could be that when syncing ALL, the return server response includes a "sync_next" parameter in the response. Once the source server receives a "complete" status on the current batch, it reads the "sync_next" parameter and begins the next batch, continuing until "sync_next" is `false`.

**Comment by phatsk** [comment]
This was addressed in https://github.com/themarcusbattle/press-sync/pull/25 by using a similar idea of a stack of objects to sync that gets shifted with each object group, the major difference being that the working implementation from #25 is in JavaScript and not PHP.
