### ISSUE TITLE
Embedded media not being synced

### ISSUE THREAD

**Issue by benjaminmueller** [marcusbattle/press-sync#5]
Media is not being synced correctly when it it embedded in the post content.

Screenshots
<img width="1478" alt="screen shot 2017-04-19 at 2 00 01 pm" src="https://cloud.githubusercontent.com/assets/2722581/25202046/c7047742-2508-11e7-83c9-b8c50b334f18.png">
<img width="1180" alt="screen shot 2017-04-19 at 1 59 25 pm" src="https://cloud.githubusercontent.com/assets/2722581/25202048/c70df98e-2508-11e7-9fc5-435bf7be0fe5.png">
<img width="1171" alt="screen shot 2017-04-19 at 1 59 41 pm" src="https://cloud.githubusercontent.com/assets/2722581/25202047/c708c13a-2508-11e7-9d2f-a20e5b976da2.png">

**Comment by themarcusbattle** [comment]
@benjaminmueller Would love for you to test this fix on your end and confirm. Thanks!
