### ISSUE TITLE
Need to load CMB2 if the plugin is not activated

### ISSUE THREAD

**Issue by jmichaelward** [marcusbattle/press-sync#8]
Press Sync has a directory for CMB2 inside includes/third-party, but it's empty. If CMB2 is not installed/activated as a plugin, form fields do not render on the Press Sync dashboard. We should probably A) include the library in case the plugin is not installed, and B) check whether the plugin is already installed or active before loading the library we included.

**Comment by themarcusbattle** [comment]
@jmichaelward wanted to update you that this is still on my radar to get patched. Development will begin on it next week.

**Comment by themarcusbattle** [comment]
Hey @jmichaelward CMB2 has been removed from the plugin in favor of native WP options. We actually ran into this recently at WDS and it was a nuicance.

**Comment by jmichaelward** [comment]
Thanks for following up, @themarcusbattle!
